// <auto-generated />
namespace ApartmentRentingPOC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Make_Room_Optional_In_Client_Object : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Make_Room_Optional_In_Client_Object));
        
        string IMigrationMetadata.Id
        {
            get { return "202006231514577_Make_Room_Optional_In_Client_Object"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
